routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MovingController@index');

// Moving Routes
Route::get('/{url}', 'MovingController@index')
    ->where('url', '(moving|Moving|MOVING|VIEW_MOVERS_RATES|FIND_MOVERS|Find_Movers|find_movers|MOVERS_NEAR_ME|Movers_Near_Me|movers_near_me)');

Route::post('/moving/send', 'MovingController@send');
Route::get('/moving/send_manually', 'MovingController@send_lead_manually');
Route::get('/moving/send_email_only_lead_to_nm', 'MovingController@send_email_only_lead_to_nm');
Route::post('/moving/saveAdditionalDetails', 'MovingController@saveAdditionalDetails');
Route::get('/moving/getLeadMatches', 'MovingController@getLeadMatches');
Route::get('/moving/confirmation', 'MovingController@confirmation');
Route::match(array('GET', 'POST'), '/unsubscribe', 'MovingController@unsubscribe');

// Validate Routes
Route::post('/validate/searchForCityState2', 'ValidateController@searchForCityState2');
Route::post('/validate/searchForCityState', 'ValidateController@searchForCityState');
Route::post('/validate/fetchCityStateByZipcode', 'ValidateController@fetchCityStateByZipcode');
Route::post('/validate/fromZipcode', 'ValidateController@fromZipcode');
Route::post('/validate/rooms', 'ValidateController@rooms');
Route::post('/validate/movedate', 'ValidateController@movedate');
Route::post('/validate/toZipcode', 'ValidateController@toZipcode');
Route::post('/validate/email', 'ValidateController@email');
Route::post('/validate/firstname', 'ValidateController@firstname');
Route::post('/validate/lastname', 'ValidateController@lastname');
Route::post('/validate/phone', 'ValidateController@phone');
Route::post('/validate/phone2', 'ValidateController@phone2');
Route::post('/validate/routeAfterHour', 'ValidateController@routeAfterHour');
Route::post('/validate/ah_popup_events', 'ValidateController@afterHoursPopupEvents');
Route::post('/validate/match_clicked', 'ValidateController@matchClicked');


// Targus Routes
Route::post('/targus', 'TargusController@doTargusNuSOAPCall');


// Twilio Routes
Route::post('/twiliosms', 'TwilioController@twiliosms');
Route::post('/twiliocall', 'TwilioController@twiliocall');
Route::post('/twilio/answer', 'TwilioController@twilioanswer');
Route::post('/twilio/hangup', 'TwilioController@twiliohangup');
Route::post('/twilio/confirmverification', 'TwilioController@confirmVerification');


// Calculate Routes
Route::post('/calc', 'CalculateController@calc');

// Contact Routes
Route::post('/contact/network_submit', 'ContactController@network_submit');
Route::post('/contact/ca_forms_submit', 'ContactController@ca_forms_submit');
Route::view('/Do-not-sell-ca', 'contact/do_not_sell');
Route::view('/right-to-know-ca', 'contact/right_to_know');
Route::view('/delete-my-info-ca', 'contact/delete_my_info');
Route::post('/contact/deleteUserInfo', 'ContactController@deleteUserInfo');


// Admin Routes
Route::get('/admin', 'AdminController@index');
Route::get('/admin/logout', 'LoginController@logout')->name('logout');
Route::get('/admin/login', 'LoginController@login')->name('login');
Route::post('/admin/login', 'LoginController@auth_user')->name('auth_user');


// TextMatch Routes
Route::resource('admin/textmatch', 'TextMatchController', ['except' => [
    'show'
]]);
Route::get('admin/textmatch/delete-confirmation/{textmatch}', 'TextMatchController@deleteConfirmation')->name('textmatch.deleteConfirmation');

app/Models/Admin/TextMatch.php
<?php

namespace App\Models\Admin;

use App\Models\Model;
use Illuminate\Support\Facades\DB;

class TextMatch extends Model
{
    protected $table = 'textmatch';
    protected $connection = 'admin';
    public $timestamps = false;

    public static $textmatch_settings;

    public static function fetchAll()
    {
        return static::all();
    }


    public static function fetchByType($type)
    {
        $resultSet = static::where('type', $type)
                            ->get();
        return !empty($resultSet) ? $resultSet : false;
    }


    public static function fetchByTypeAndText($type, $text)
    {
        $resultSet = static::where([
                            ['type', $type],
                            ['text', $text]
                        ])
                        ->count();
        return !empty($resultSet) ? true : false;
    }

    public static function isExactName($value)
    {
        if (self::$textmatch_settings && self::$textmatch_settings->exact_name == 0) {
            return false;
        }

        return static::fetchByTypeAndText('exact', $value);
    }

    public static function isFullEmail($value)
    {
        if (self::$textmatch_settings && self::$textmatch_settings->full_email == 0) {
            return false;
        }
        return static::fetchByTypeAndText('full-email', $value);
    }

    public static function isAddressEmail($value)
    {
        if (self::$textmatch_settings && self::$textmatch_settings->address_email == 0) {
            return false;
        }
        return static::fetchByTypeAndText('address-email', $value);
    }

    public static function isDomainEmail($value)
    {
        if (self::$textmatch_settings && self::$textmatch_settings->domain_email == 0) {
            return false;
        }
        return static::fetchByTypeAndText('domain-email', $value);
    }

    public static function check_three_repeating_characters($name)
    {
        $last_letter = '';
        $letter_count = 1;
        $arr_name = str_split($name);
        foreach ($arr_name as $letter) {
            if (strcasecmp($last_letter, $letter) == 0) {
                $letter_count++;
            } else {
                $letter_count = 1;
            }

            if ($letter_count >= 3) {
                return true;
            }

            $last_letter = $letter;
        }
        return false;
    }

    public static function setTextMatchSettingsTable()
    {
        self::$textmatch_settings = DB::table('textmatch_settings')->first();
    }

    public static function isNameSet($first_name, $last_name)
    {
        if (self::$textmatch_settings && self::$textmatch_settings->name_set == 0) {
            return false;
        }

        $value = trim($first_name) . ' ' . trim($last_name);
        return static::fetchByTypeAndText('name-set', $value);
    }
}

app/Http/Controllers/TextMatchController.php
<?php

namespace App\Http\Controllers;

use App\Models\Admin\TextMatch;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class TextMatchController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view(
            'admin.textmatch.index',
            [
                'textmatches' => [
                    'exact' => [
                        'name' => 'Exact Match',
                        'data' => TextMatch::fetchByType('exact'),
                    ],
                    'name_set' => [
                        'name' => 'Name Set Match',
                        'data' => TextMatch::fetchByType('name-set'),
                    ],
                    'full_email' => [
                        'name' => 'Full Email Match',
                        'data' => TextMatch::fetchByType('full-email'),
                    ],
                    'address_email' => [
                        'name' => 'Address Email Match',
                        'data' => TextMatch::fetchByType('address-email'),
                    ],
                    'domain_email' => [
                        'name' => 'Domain Email Match',
                        'data' => TextMatch::fetchByType('domain-email'),
                    ],
            ]]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.textmatch.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'type' => [
                'required',
                Rule::in(['exact', 'name-set', 'full-email', 'address-email', 'domain-email'])
            ],
            'text' => 'required',
        ]);

        TextMatch::create([
            'type' => $request->input('type'),
            'text' => $request->input('text'),
            'date_time' => date('Y-m-d H:i:s')
        ]);

        return redirect('admin/textmatch');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Admin\TextMatch  $textMatch
     * @return \Illuminate\Http\Response
     */
    public function edit(TextMatch $textmatch)
    {
        return view('admin.textmatch.edit', compact('textmatch'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Admin\TextMatch  $textMatch
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TextMatch $textmatch)
    {
        $this->validate($request, [
            'text' => 'required'
        ]);

        $textmatch->text = $request->input('text');
        $textmatch->date_time = date('Y-m-d H:i:s');
        $textmatch->save();

        return redirect('admin/textmatch');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Admin\TextMatch  $textMatch
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, TextMatch $textmatch)
    {
        if ($request->input('del', 'No') == 'Yes') {
            $textmatch->delete();
        }
        
        return redirect('admin/textmatch');
    }


    public function deleteConfirmation(TextMatch $textmatch)
    {
        return view('admin.textmatch.delete-confirmation', compact('textmatch'));
    }
}

resources/views/admin/textmatch/create.blade.php
@extends('layouts.admin.master')

@section('title', 'Add Textmatch')

@section('content')

@include('layouts.errors')


<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				@yield('title')
			</div>
			<div class="panel-body">
				<form action="{{ route('textmatch.store') }}" method="POST" name="textmatch" class="field-group" id="textmatch">
					{{ csrf_field() }}
					<input type="hidden" name="id" value="" />
					<div class="form-group">
						<label>
							<span>Match Type</span>
							<select name="type" class="form-control">
								<option value="exact">exact</option>
								<option value="name-set">name-set</option>
								<option value="full-email">full-email</option>
								<option value="address-email">address-email</option>
								<option value="domain-email">domain-email</option>
							</select>
						</label>
					</div>
					<div class="form-group">
						<label for="text">Text List</label>
						<textarea name="text" class="form-control"></textarea>
					</div>
					<div class="form-group">
						<input type="submit" name="submit" id="add_textmatch" class="btn btn-primary" value="Add" />
					</div>
				</form>
			</div>
		</div>
	</div>
</div>


@endsection

resources/views/admin/textmatch/delete-confirmation.blade.php
@extends('layouts.admin.master')

@section('title', 'Delete Textmatch')

@section('content')

@include('layouts.errors')


<div class="row">
	<div class="col-md-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				@yield('title')
			</div>
			<div class="panel-body">
				<form action="{{ route('textmatch.destroy', $textmatch) }}" class="field-group" method="post">
					{{ method_field('DELETE') }}
					{{ csrf_field() }}
					<p>Are you sure that you want to delete
					'{{ $textmatch->text }}'
					</p>
					<div>						
						<input type="submit" class="btn btn-primary" name="del" value="Yes" />
						<input type="submit" class="btn btn-default" name="del" value="No" />
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/textmatch/edit.blade.php
@extends('layouts.admin.master')

@section('title', 'Edit Textmatch')

@section('content')

@include('layouts.errors')

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				@yield('title')
			</div>
			<div class="panel-body">
				<form action="{{ route('textmatch.update', $textmatch) }}" method="POST" name="textmatch" class="field-group" id="textmatch">
					{{ method_field('PATCH') }}
					{{ csrf_field() }}
					<input type="hidden" name="id" value="{{$textmatch->id}}">
					<input type="hidden" name="type" class="form-control" value="{{$textmatch->type}}">
					<div class="form-group">
						<label for="text">Text List</label>
						<textarea name="text" class="form-control">{{ $textmatch->text }}</textarea>
					</div>
					<div class="form-group">
						<input type="submit" name="submit" id="add_textmatch" class="btn btn-primary" value="Edit">
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/textmatch/index.blade.php
@extends('layouts.admin.master')

@section('title', 'Textmatch List')

@section('content')


<div class="row">
	<div class="col-md-12">
		<div class="well">
			<a class="btn btn-primary" href="{{ route('textmatch.create') }}">Add Textmatch</a>
		</div>
	</div>
</div>

@foreach ($textmatches as $type)
	@if(isset($type['data']) && $type['data']->count())
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-primary">
					<div class="panel-heading">{{ $type['name'] }}</div>
					<div style="max-height: 187px; overflow-y: scroll;">
						<table class="table table-bordered">
							<thead>
								<tr>
									<th>Text</th>
									<th>Date</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@foreach ($type['data'] as $textmatch)
								<tr>
									<td>{{ $textmatch->text }}</td>
									<td>{{ date('l (M d, Y)',strtotime($textmatch->date_time)) }}</td>
									<td>
										<a href="{{ route('textmatch.edit', $textmatch) }}">Edit</a>
										<a href="{{ route('textmatch.deleteConfirmation', $textmatch) }}">Delete</a>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>	
		</div>
	@endif
@endforeach


@endsection